n1 = int(input("digite um número:"))
n2 = int(input("digite outro número:"))
print(f"a soma de {n1} e {n2} é {n1+n2}")
print(f"a subtração de {n1} e {n2} é {n1-n2}")
print(f" multiplicação de {n1} e {n2} é {n1*n2}")
print(f"a divisão de {n1} e {n2} é {n1/n2}")
